### PR TITLE
Vary middleware

### PR DESCRIPTION
**Pull request by imbolc**
Here's how it looks (just a draft yet). Let me know if you're ok with the approach before I finish it.

Also I've noticed you implemented tower middleware in the guard, is there any benefits compared to `axum::middleware::from_fn`. I can't imagine how one would use the crate without axum, so depending on it instead of `axum-core` seems ok, isn't it?

### CODE REVIEW

**Comment by imbolc** [comment]
@robertwayne haven't had a chance to look at it yet?

**Comment by robertwayne** [comment]
Yeah, I'm good with this approach. It's about what I envisioned when you originally brought up channels. You can finish This should live behind a feature, for sure.

> Also I've noticed you implemented tower middleware in the guard, is there any benefits compared to axum::middleware::from_fn. I can't imagine how one would use the crate without axum, so depending on it instead of axum-core seems ok, isn't it?

Yeah, it certainly could have used the axum `from_fn` method. I just chose to go with the most flexible (and lowest level) option available after initially reading through the axum middleware documentation.

**Comment by imbolc** [comment]
@robertwayne just making sure you don't miss it, no hurry

**Comment by robertwayne** [comment]
Thanks for the ping (and the work on this)!

This looks great to me; tests, docs, and example. Thank you again!

**Review by robertwayne — APPROVED** [review]

**Pull request merged**
