### PR TITLE
Merged serde responders to remove code duplication

### PR DESCRIPTION
**Pull request by ItsEthra**
## List of changes:
- Removed `responders::serde`, now all triggers in `responders` module use `HxEvent` which has additional `data` fields when `serde` feature is enabled.
- Removed `responders::serde::HxLocation`, now `responders::HxLocation` is a struct with a `uri` field and additional `options` field when `serde` feature is enabled.
- `HxResponseTrigger*` responders are now in `responders/trigger.rs`, `HxLocation` responder is now in `responders/location.rs`.
- Implemented `TryFrom<&str>` for uri-like responders.
- Renamed `HxError::Serialization` to `HxError::Json`.
- Added test for `HxLocation` serialization.
- Do not add `HxResponseTrigger*` header if there are no events.

## Unresolved questions:
- [ ] ~~Maybe it's better to renamed `HxResponseTrigger*` to `HxTrigger*` and not reexport everything in `lib.rs`?~~
- `HxCurrentUrl` extractor can also use uri instead of string, what should happen if header is not valid uri? (one approach would be to just do `None`)
- `HxResponseTrigger*` can be further de-duplicated using either a enum/struct with enum tag/struct with marker. 
```rs
// enum
enum HxResponseTrigger {
    Normal(Vec<HxEvent>),
    AfterSwap(Vec<HxEvent>),
    AfterSettle(Vec<HxEvent>),
}
// usage
HxResponseTrigger::AfterSwap(vec!["my-event".into()]);

// struct with enum tag
struct HxTrigger [
    events: Vec<HxEvent>,
    mode: TriggerMode,
}
// usage
HxTrigger {
    events: vec!["my-event".into()],
    mode: TriggerMode::Foo,
};
// downside: cumbersome to create

enum TriggerMode {
    Normal,
    AfterSettle,
    AfterSwap,
}

// struct with marker
struct Normal;
struct AfterSettle;
struct AfterSwap;

struct HxTrigger<M> {
    events: Vec<HxEvent>,
    _mode: PhantomData<M>
}
// usage
HxTrigger::<Normal>::from(["foo", "bar"]);
```

### CODE REVIEW

**Comment by ItsEthra** [comment]
> Obviously there are a lot of benefits to not re-exporting in general, but I'm not particularly sold on it overall.

Sure we can keep it as is.

Given that htmx sets header to correct value and the only way to pass incorrect uri would be to make request manually, I think it's reasonable to just discard the error and return `None`. 

Now for HxResponseTrigger I have a favor in doing it with marker struct approach. We don't really need an enum because user will likely never need to match as it's a response header. It will also take more space than generic struct. I could do it as a normal struct but again, we don't really need to store mode, as user will never check it at runtime. The only thing we need mode for is to figure out appropriate header name so it makes sense to do it via generics at compile time. Size increase also applies to normal struct but not generic struct.

So if you are okay with those solutions I can go ahead and implement it.

**Comment by ItsEthra** [comment]
Done, Implemented `HxResponseTrigger` with using a struct with some helper methods. Replaced `HxCurrentUrl` to use `http::Uri`, also hid `ResponseFuture` type because user doesn't really need it. Also, what do you think about marking root reexports as `doc(inline)` so It would appear as all modules' contents are in root itself? It will look something like this 
image

**Comment by robertwayne** [comment]
> Also, what do you think about marking root reexports as doc(inline) so It would appear as all modules' contents are in root itself?

Let's do that!

I'll review the rest of this in a moment, but from a glance it looks solid.

**Comment by ItsEthra** [comment]
Done, I inlined reexports and also tweaked `HxError` type, now it can be used with `anyhow` and other error handling crates.

**Pull request merged**
